kind: Namespace
apiVersion: v1
metadata:
  name: helloworld-demo
---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          # enter the path to your image, be sure to include the correct region prefix
          image: iad.ocir.io/idttmev3z6fl/anjhjha
          ports:
            - containerPort: 8888
              protocol: TCP

